#' The values Element accepts for its enumerated props
#'
#' Generated by `tools/ep-choices.py` from Element Plus 2.14.7's API tables:
#' every argument that is an enumerated prop upstream, with no free-form
#' alternative (an `effect` that also takes any string is not checked). A
#' prop that also takes a number -- an avatar's `size` -- is checked only
#' when given a string.
#'
#' @name .el_choices
#' @keywords internal
.el_choices <- local({
  list(
    el_alert = list(effect = c("light", "dark")),
    el_autocomplete = list(placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end")),
    el_avatar = list(size = c("large", "default", "small"), shape = c("circle", "square"), fit = c("fill", "contain", "cover", "none", "scale-down")),
    el_badge = list(type = c("primary", "success", "warning", "danger", "info")),
    el_button = list(size = c("large", "default", "small"), native_type = c("button", "submit", "reset")),
    el_calendar = list(controller_type = c("button", "select")),
    el_carousel = list(trigger = c("hover", "click"), indicator_position = c("", "none", "outside"), arrow = c("always", "hover", "never"), type = c("", "card"), direction = c("horizontal", "vertical")),
    el_cascader = list(size = c("large", "default", "small"), tag_type = c("success", "info", "warning", "danger"), tag_effect = c("light", "dark", "plain"), placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end"), show_checked_strategy = c("parent", "child")),
    el_checkbox = list(size = c("large", "default", "small")),
    el_checkbox_group = list(size = c("large", "default", "small"), type = c("checkbox", "button")),
    el_color_picker = list(size = c("large", "default", "small"), color_format = c("rgb", "prgb", "hex", "hex3", "hex4", "hex6", "hex8", "name", "hsl", "hsv")),
    el_container = list(direction = c("horizontal", "vertical")),
    el_date_picker = list(size = c("", "large", "default", "small"), type = c("year", "years", "month", "months", "date", "dates", "datetime", "week", "quarter", "quarters", "datetimerange", "daterange", "monthrange", "yearrange", "quarterrange")),
    el_descriptions = list(direction = c("vertical", "horizontal"), size = c("", "large", "default", "small")),
    el_divider = list(direction = c("horizontal", "vertical"), content_position = c("left", "right", "center")),
    el_drawer = list(direction = c("rtl", "ltr", "ttb", "btt")),
    el_dropdown = list(size = c("", "large", "default", "small"), placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end"), role = c("dialog", "grid", "group", "listbox", "menu", "navigation", "tooltip", "tree")),
    el_form = list(label_position = c("left", "right", "top"), require_asterisk_position = c("left", "right"), size = c("", "large", "default", "small")),
    el_image = list(fit = c("", "fill", "contain", "cover", "none", "scale-down"), loading = c("eager", "lazy"), crossorigin = c("", "anonymous", "use-credentials")),
    el_input = list(word_limit_position = c("inside", "outside"), size = c("large", "default", "small"), resize = c("none", "both", "horizontal", "vertical")),
    el_input_number = list(size = c("large", "default", "small"), controls_position = c("", "right"), align = c("left", "center", "right")),
    el_link = list(type = c("primary", "success", "warning", "danger", "info", "default")),
    el_menu = list(mode = c("horizontal", "vertical"), menu_trigger = c("hover", "click")),
    el_notification = list(position = c("top-right", "top-left", "bottom-right", "bottom-left")),
    el_pagination = list(size = c("large", "default", "small")),
    el_popconfirm = list(confirm_button_type = c("primary", "success", "warning", "danger", "info", "text"), cancel_button_type = c("primary", "success", "warning", "danger", "info", "text")),
    el_popover = list(placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end")),
    el_progress = list(type = c("line", "circle", "dashboard"), status = c("success", "exception", "warning"), stroke_linecap = c("butt", "round", "square")),
    el_radio_group = list(type = c("radio", "button")),
    el_rate = list(size = c("large", "default", "small")),
    el_row = list(justify = c("start", "end", "center", "space-around", "space-between", "space-evenly"), align = c("top", "middle", "bottom")),
    el_select = list(size = c("", "large", "default", "small"), tag_type = c("", "success", "info", "warning", "danger"), tag_effect = c("", "light", "dark", "plain"), placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end")),
    el_slider = list(size = c("", "large", "default", "small"), input_size = c("", "large", "default", "small"), placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end")),
    el_steps = list(direction = c("vertical", "horizontal"), process_status = c("wait", "process", "finish", "error", "success"), finish_status = c("wait", "process", "finish", "error", "success")),
    el_switch = list(size = c("", "large", "default", "small")),
    el_table = list(size = c("", "large", "default", "small"), tooltip_effect = c("dark", "light"), table_layout = c("fixed", "auto")),
    el_tabs = list(type = c("", "card", "border-card"), tab_position = c("top", "right", "bottom", "left")),
    el_tag = list(type = c("primary", "success", "info", "warning", "danger"), size = c("large", "default", "small"), effect = c("dark", "light", "plain")),
    el_time_picker = list(size = c("large", "default", "small")),
    el_time_select = list(size = c("large", "default", "small")),
    el_timeline = list(mode = c("start", "alternate", "alternate-reverse", "end")),
    el_tooltip = list(effect = c("dark", "light"), placement = c("top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end")),
    el_transfer = list(target_order = c("original", "push", "unshift")),
    el_upload = list(crossorigin = c("", "anonymous", "use-credentials"), list_type = c("text", "picture", "picture-card"))
  )
})

#' Refuse a value Element does not accept
#'
#' Called first thing by every component with an enumerated argument: a
#' typo -- `type = "primry"` -- is an error naming the values that work,
#' rather than a component Element quietly draws in its default style.
#' Exact matching, unlike [match.arg()]: `"prim"` is not `"primary"` to
#' Element either.
#'
#' @param fn The function's name, a key of [.el_choices].
#' @param env Its evaluation environment.
#' @return `NULL`, invisibly; or an error.
#' @keywords internal
.el_check_choices <- function(fn, env) {
  allowed <- .el_choices[[fn]]
  for (arg in names(allowed)) {
    if (!exists(arg, envir = env, inherits = FALSE)) next
    value <- get(arg, envir = env, inherits = FALSE)
    if (is.null(value) || (length(value) == 1L && is.na(value))) next
    if (is.numeric(value)) next
    if (!is.character(value) || length(value) != 1L || !value %in% allowed[[arg]]) {
      stop(sprintf("`%s` should be one of %s, not %s.", arg,
                   paste0('"', allowed[[arg]], '"', collapse = ", "),
                   paste(deparse(value), collapse = "")),
           call. = FALSE)
    }
  }
  invisible(NULL)
}
