# Generated by tools/events-registry.py -- edit that, not this.
#
# Every Shiny input each component reports: `inputs`, always reported,
# by suffix ("" for input$<id> itself); `events`, Element's events it
# forwards as input$<id>_<event>, `default` the ones reported unasked.
# Descriptions and arguments are Element Plus's own.

.el_event_registry <- list(
  el_affix = list(
    inputs = list(),
    events = list(
      list(event = "change", default = TRUE, about = "triggers when fixed state changed", args = "(fixed: boolean)", value = ""),
      list(event = "scroll", default = FALSE, about = "triggers when scrolling", args = "(value: { scrollTop: number, fixed: boolean })", value = "`list(scrollTop, fixed)`, at most every 200 ms")
    )
  ),
  el_alert = list(
    inputs = list(
      list(input = "close", about = "fires when the user closes the alert")
    ),
    events = list()
  ),
  el_anchor = list(
    inputs = list(
      list(input = "", about = "the `href` of the current link, as the page scrolls")
    ),
    events = list(
      list(event = "click", default = FALSE, about = "Triggered when the user clicks on the link", args = "(e: MouseEvent, href?: string)", value = "the `href` of the link clicked")
    )
  ),
  el_autocomplete = list(
    inputs = list(
      list(input = "", about = "the current text"),
      list(input = "query", about = "with `remote = TRUE`, the text to suggest for; answer with `update_el_autocomplete()`")
    ),
    events = list(
      list(event = "select", default = TRUE, about = "triggers when a suggestion is clicked", args = "(item: Record<string, any>)", value = ""),
      list(event = "change", default = FALSE, about = "triggers when the icon inside Input value change", args = "(value: string | number)", value = ""),
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the Input is cleared by clicking the clear button", args = "()", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "input", default = FALSE, about = "triggers when the Input value change", args = "(value: string | number)", value = "")
    )
  ),
  el_avatar = list(
    inputs = list(),
    events = list(
      list(event = "error", default = TRUE, about = "trigger when image load error.", args = "(e: Event)", value = "")
    )
  ),
  el_backtop = list(
    inputs = list(),
    events = list(
      list(event = "click", default = TRUE, about = "triggers when click.", args = "(evt: MouseEvent)", value = "")
    )
  ),
  el_breadcrumb = list(
    inputs = list(
      list(input = "", about = "the `label` of the step last clicked")
    ),
    events = list()
  ),
  el_button = list(
    inputs = list(
      list(input = "", about = "the number of clicks, as `actionButton()` reports it")
    ),
    events = list()
  ),
  el_calendar = list(
    inputs = list(
      list(input = "", about = "the day picked, `\"YYYY-MM-DD\"`"),
      list(input = "dates", about = "the month shown: `list(current, start, end)`, Dates"),
      list(input = "click", about = "an event clicked"),
      list(input = "add", about = "a new event the user saved (`editable`); answer with `update_el_calendar(insert =)`"),
      list(input = "update", about = "an edit or a move: `list(event, changes)`; answer with `update_el_calendar(replace =)`"),
      list(input = "delete", about = "an event the user deleted; answer with `update_el_calendar(delete =)`")
    ),
    events = list()
  ),
  el_carousel = list(
    inputs = list(
      list(input = "", about = "the index of the slide showing, from 0"),
      list(input = "name", about = "its `name`, if it has one")
    ),
    events = list()
  ),
  el_cascader = list(
    inputs = list(
      list(input = "", about = "the selected path"),
      list(input = "lazy_load", about = "with `props = list(lazy = TRUE)`, a column to load; answer with `el_load_children()`")
    ),
    events = list(
      list(event = "expand-change", default = FALSE, about = "triggers when expand option changes", args = "(value: CascaderValue)", value = ""),
      list(event = "blur", default = FALSE, about = "triggers when Cascader blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Cascader focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "visible-change", default = FALSE, about = "triggers when the dropdown appears/disappears", args = "(value: boolean)", value = ""),
      list(event = "remove-tag", default = FALSE, about = "triggers when remove tag in multiple selection mode", args = "(value: CascaderNode['valueByOption'])", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked in a clearable Select", args = "()", value = "")
    )
  ),
  el_cascader_panel = list(
    inputs = list(
      list(input = "", about = "the selected path"),
      list(input = "lazy_load", about = "with `props = list(lazy = TRUE)`, a column to load; answer with `el_load_children()`")
    ),
    events = list(
      list(event = "expand-change", default = FALSE, about = "triggers when expand option changes", args = "(value: CascaderNodePathValue)", value = ""),
      list(event = "close", default = FALSE, about = "close panel event, provided to Cascader to put away the panel judgment.", args = "()", value = "")
    )
  ),
  el_check_tag = list(
    inputs = list(
      list(input = "", about = "`TRUE` while checked")
    ),
    events = list()
  ),
  el_checkbox = list(
    inputs = list(
      list(input = "", about = "`TRUE` or `FALSE`, or `true_value` and `false_value`")
    ),
    events = list()
  ),
  el_checkbox_group = list(
    inputs = list(
      list(input = "", about = "the values checked")
    ),
    events = list()
  ),
  el_collapse = list(
    inputs = list(
      list(input = "", about = "the names of the open panels")
    ),
    events = list()
  ),
  el_color_picker = list(
    inputs = list(
      list(input = "", about = "the colour")
    ),
    events = list(
      list(event = "active-change", default = FALSE, about = "triggers when the current active color changes", args = "(value: string)", value = "the colour being picked, at most every 200 ms"),
      list(event = "blur", default = FALSE, about = "triggers when Component blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear button is clicked", args = "()", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Component focuses", args = "(event: FocusEvent)", value = "")
    )
  ),
  el_color_picker_panel = list(
    inputs = list(
      list(input = "", about = "the colour")
    ),
    events = list()
  ),
  el_countdown = list(
    inputs = list(),
    events = list(
      list(event = "finish", default = TRUE, about = "countdown end event", args = "()", value = ""),
      list(event = "change", default = FALSE, about = "Time difference change event", args = "(value: number)", value = "the milliseconds left, at most once a second")
    )
  ),
  el_date_picker = list(
    inputs = list(
      list(input = "", about = "the date, two for a range")
    ),
    events = list(
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(e: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(e: FocusEvent)", value = ""),
      list(event = "calendar-change", default = FALSE, about = "triggers when the calendar selected date is changed. Only for range", args = "(val: [Date, null | Date])", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when a clear button is clicked", args = "()", value = ""),
      list(event = "panel-change", default = FALSE, about = "triggers when the navigation button click.", args = "(date: Date | [Date, Date], mode: 'month' | 'year', view?: string)", value = ""),
      list(event = "visible-change", default = FALSE, about = "triggers when the DatePicker's dropdown appears/disappears", args = "(visibility: boolean)", value = "")
    )
  ),
  el_date_picker_panel = list(
    inputs = list(
      list(input = "", about = "the date, two for a range")
    ),
    events = list(
      list(event = "calendar-change", default = FALSE, about = "triggers when the calendar selected date is changed. Only for range", args = "(val: [Date, null | Date])", value = ""),
      list(event = "panel-change", default = FALSE, about = "triggers when the navigation button click.", args = "(date: Date | [Date, Date], mode: 'month' | 'year', view?: string)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when a clear button is clicked", args = "()", value = "")
    )
  ),
  el_dialog = list(
    inputs = list(
      list(input = "", about = "`TRUE` while it is open")
    ),
    events = list(
      list(event = "open", default = FALSE, about = "triggers when the Dialog opens", args = "()", value = ""),
      list(event = "opened", default = FALSE, about = "triggers when the Dialog opening animation ends", args = "()", value = ""),
      list(event = "close", default = FALSE, about = "triggers when the Dialog closes", args = "()", value = ""),
      list(event = "closed", default = TRUE, about = "triggers when the Dialog closing animation ends", args = "()", value = ""),
      list(event = "open-auto-focus", default = FALSE, about = "triggers after Dialog opens and content focused", args = "()", value = ""),
      list(event = "close-auto-focus", default = FALSE, about = "triggers after Dialog closed and content focused", args = "()", value = "")
    )
  ),
  el_drawer = list(
    inputs = list(
      list(input = "", about = "`TRUE` while it is open")
    ),
    events = list(
      list(event = "open", default = FALSE, about = "Triggered before Drawer opening animation begins", args = "()", value = ""),
      list(event = "opened", default = FALSE, about = "Triggered after Drawer opening animation ended", args = "()", value = ""),
      list(event = "close", default = FALSE, about = "Triggered before Drawer closing animation begins", args = "()", value = ""),
      list(event = "closed", default = TRUE, about = "Triggered after Drawer closing animation ended", args = "()", value = ""),
      list(event = "open-auto-focus", default = FALSE, about = "triggers after Drawer opens and content focused", args = "()", value = ""),
      list(event = "close-auto-focus", default = FALSE, about = "triggers after Drawer closed and content focused", args = "()", value = ""),
      list(event = "resize-start", default = FALSE, about = "Triggered when resizing starts (when resizable is enabled)", args = "(evt: MouseEvent, size: number)", value = "the size, in pixels"),
      list(event = "resize", default = FALSE, about = "Triggered while resizing (when resizable is enabled)", args = "(evt: MouseEvent, size: number)", value = "the size, in pixels"),
      list(event = "resize-end", default = FALSE, about = "Triggered when resizing ends (when resizable is enabled)", args = "(evt: MouseEvent, size: number)", value = "the size, in pixels")
    )
  ),
  el_dropdown = list(
    inputs = list(
      list(input = "", about = "the `command` of the item clicked, as an event"),
      list(input = "count", about = "the number of items clicked")
    ),
    events = list(
      list(event = "click", default = TRUE, about = "if split-button is true, triggers when left button is clicked", args = "(e: MouseEvent)", value = ""),
      list(event = "visible-change", default = FALSE, about = "triggers when the dropdown appears/disappears, the param is true when it appears, and false otherwise", args = "(val: boolean)", value = "")
    )
  ),
  el_form = list(
    inputs = list(
      list(input = "", about = "the whole model, on load and on every submit"),
      list(input = "valid", about = "`TRUE` when the last submit passed validation"),
      list(input = "submit", about = "a submit counter")
    ),
    events = list(
      list(event = "validate", default = FALSE, about = "triggers after a form item is validated", args = "(prop: FormItemProp, isValid: boolean, message: string)", value = "")
    )
  ),
  el_image = list(
    inputs = list(),
    events = list(
      list(event = "load", default = FALSE, about = "same as native load.", args = "(e: Event)", value = ""),
      list(event = "error", default = TRUE, about = "same as native error.", args = "(e: Event)", value = ""),
      list(event = "close", default = FALSE, about = "trigger when clicking on close button or when hide-on-click-modal enabled clicking on backdrop.", args = "()", value = ""),
      list(event = "show", default = FALSE, about = "trigger when the viewer displays", args = "()", value = ""),
      list(event = "switch", default = FALSE, about = "trigger when switching images.", args = "(index: number)", value = "")
    )
  ),
  el_image_viewer = list(
    inputs = list(
      list(input = "close", about = "fires as it closes")
    ),
    events = list(
      list(event = "error", default = TRUE, about = "same as native error.", args = "(e: Event)", value = ""),
      list(event = "switch", default = FALSE, about = "trigger when switching images.", args = "(index: number)", value = ""),
      list(event = "rotate", default = FALSE, about = "trigger when rotating images.", args = "(deg: number)", value = "")
    )
  ),
  el_infinite_scroll = list(
    inputs = list(
      list(input = "load", about = "rises by one each time more content is wanted")
    ),
    events = list()
  ),
  el_input = list(
    inputs = list(
      list(input = "", about = "the text, as it is typed (debounced by 250 ms)")
    ),
    events = list(
      list(event = "input", default = FALSE, about = "triggers when the Input value change", args = "(value: string | number)", value = ""),
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the Input is cleared by clicking the clear button", args = "(evt?: MouseEvent) => void (After version 2.13.4, the evt parameter can be received)", value = ""),
      list(event = "compositionend", default = FALSE, about = "triggers when the composition ends", args = "(event: CompositionEvent)", value = ""),
      list(event = "compositionstart", default = FALSE, about = "triggers when the composition starts", args = "(event: CompositionEvent)", value = ""),
      list(event = "compositionupdate", default = FALSE, about = "triggers when the composition is updated", args = "(event: CompositionEvent)", value = ""),
      list(event = "keydown", default = FALSE, about = "triggers when a key is pressed down", args = "(event: KeyboardEvent | Event)", value = "the key: `list(key, code, ctrl, shift, alt, meta)`"),
      list(event = "mouseenter", default = FALSE, about = "triggers when the mouse enters the Input element", args = "(event: MouseEvent)", value = ""),
      list(event = "mouseleave", default = FALSE, about = "triggers when the mouse leaves the Input element", args = "(event: MouseEvent)", value = "")
    )
  ),
  el_input_number = list(
    inputs = list(
      list(input = "", about = "the number")
    ),
    events = list(
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(event: FocusEvent)", value = "")
    )
  ),
  el_input_otp = list(
    inputs = list(
      list(input = "", about = "the value")
    ),
    events = list(
      list(event = "change", default = FALSE, about = "Triggers when the value changes after input blur", args = "(value: string)", value = ""),
      list(event = "finish", default = TRUE, about = "Fires when all fields have been filled", args = "(value: string)", value = ""),
      list(event = "focus", default = FALSE, about = "Triggers when input is focused", args = "(event: FocusEvent)", value = ""),
      list(event = "blur", default = FALSE, about = "Triggers when input is blurred", args = "(event: FocusEvent)", value = "")
    )
  ),
  el_input_tag = list(
    inputs = list(
      list(input = "", about = "the tags")
    ),
    events = list(
      list(event = "input", default = FALSE, about = "triggers when the input value change", args = "(value: string)", value = ""),
      list(event = "add-tag", default = FALSE, about = "triggers when a tag is added", args = "(value: string | string [])", value = ""),
      list(event = "remove-tag", default = FALSE, about = "triggers when a tag is removed", args = "(value: string, index: number)", value = ""),
      list(event = "drag-tag", default = FALSE, about = "triggers when a tag is dragged", args = "(oldIndex: number, newIndex: number, value: string)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when InputTag focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "blur", default = FALSE, about = "triggers when InputTag blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked", args = "()", value = "")
    )
  ),
  el_link = list(
    inputs = list(
      list(input = "", about = "with an `id`, the number of clicks, as `actionLink()` reports it")
    ),
    events = list()
  ),
  el_mention = list(
    inputs = list(
      list(input = "", about = "the text")
    ),
    events = list(
      list(event = "search", default = TRUE, about = "trigger when prefix hit", args = "(pattern: string, prefix: string)", value = "`list(pattern, prefix)`; answer with `update_el_mention(options =)`"),
      list(event = "select", default = TRUE, about = "trigger when user select the option", args = "(option: MentionOption, prefix: string)", value = "`list(option, prefix)`"),
      list(event = "whole-remove", default = FALSE, about = "trigger when a whole mention is removed and whole is true or check-is-whole is true", args = "(pattern: string, prefix: string)", value = "`list(pattern, prefix)`")
    )
  ),
  el_menu = list(
    inputs = list(
      list(input = "", about = "the `index` of the selected item"),
      list(input = "path", about = "the indexes down to it")
    ),
    events = list(
      list(event = "open", default = FALSE, about = "callback function when sub-menu expands", args = "MenuOpenEvent", value = "`list(index, path)` of the submenu"),
      list(event = "close", default = FALSE, about = "callback function when sub-menu collapses", args = "MenuCloseEvent", value = "`list(index, path)` of the submenu")
    )
  ),
  el_page_header = list(
    inputs = list(),
    events = list(
      list(event = "back", default = TRUE, about = "triggers when right side is clicked", args = "()", value = "")
    )
  ),
  el_pagination = list(
    inputs = list(
      list(input = "", about = "the current page, from 1"),
      list(input = "page_size", about = "the page size")
    ),
    events = list(
      list(event = "prev-click", default = FALSE, about = "triggers when the prev button is clicked and current page changes", args = "(value: number)", value = ""),
      list(event = "next-click", default = FALSE, about = "triggers when the next button is clicked and current page changes", args = "(value: number)", value = ""),
      list(event = "change", default = FALSE, about = "triggers when current-page or page-size changes", args = "(currentPage: number, pageSize: number)", value = "")
    )
  ),
  el_popconfirm = list(
    inputs = list(
      list(input = "confirm", about = "fires when the user confirms"),
      list(input = "cancel", about = "fires when the user backs out")
    ),
    events = list()
  ),
  el_popover = list(
    inputs = list(),
    events = list(
      list(event = "show", default = FALSE, about = "triggers when popover shows", args = "()", value = ""),
      list(event = "hide", default = FALSE, about = "triggers when popover hides", args = "()", value = ""),
      list(event = "after-enter", default = FALSE, about = "triggers when the entering transition ends", args = "()", value = ""),
      list(event = "after-leave", default = FALSE, about = "triggers when the leaving transition ends", args = "()", value = ""),
      list(event = "before-enter", default = FALSE, about = "triggers when the entering transition before", args = "()", value = ""),
      list(event = "before-leave", default = FALSE, about = "triggers when the leaving transition before", args = "()", value = "")
    )
  ),
  el_radio_group = list(
    inputs = list(
      list(input = "", about = "the value picked")
    ),
    events = list()
  ),
  el_rate = list(
    inputs = list(
      list(input = "", about = "the rating")
    ),
    events = list()
  ),
  el_scrollbar = list(
    inputs = list(),
    events = list(
      list(event = "scroll", default = FALSE, about = "triggers when scrolling, return distance of scrolling", args = "({ scrollLeft: number, scrollTop: number })", value = "`list(scrollLeft, scrollTop)`, at most every 200 ms"),
      list(event = "end-reached", default = TRUE, about = "triggers when the end of a scroll is triggered", args = "(direction: 'top' | 'bottom' | 'left' | 'right')", value = "")
    )
  ),
  el_segmented = list(
    inputs = list(
      list(input = "", about = "the value")
    ),
    events = list()
  ),
  el_select = list(
    inputs = list(
      list(input = "", about = "the value, several with `multiple`"),
      list(input = "query", about = "with `remote = TRUE`, the text typed; answer with `update_el_select(choices =)`")
    ),
    events = list(
      list(event = "visible-change", default = FALSE, about = "triggers when the dropdown appears/disappears", args = "(visible: boolean)", value = ""),
      list(event = "remove-tag", default = FALSE, about = "triggers when a tag is removed in multiple mode", args = "(tagValue: any)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked in a clearable Select", args = "()", value = ""),
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "end-reached", default = TRUE, about = "triggers when dropdown scroll reaches an end", args = "(direction: 'top' | 'bottom' | 'left' | 'right')", value = ""),
      list(event = "popup-scroll", default = FALSE, about = "triggers when dropdown scrolls", args = "(data:{scrollTop: number, scrollLeft: number})", value = "`list(scroll_left, scroll_top)`, at most every 200 ms")
    )
  ),
  el_select_v2 = list(
    inputs = list(
      list(input = "", about = "the value, several with `multiple`")
    ),
    events = list(
      list(event = "visible-change", default = FALSE, about = "triggers when the dropdown appears/disappears, the param will be true when it appears, and false otherwise", args = "(visible: boolean)", value = ""),
      list(event = "remove-tag", default = FALSE, about = "triggers when a tag is removed in multiple mode, the param is removed tag value", args = "(tagValue: any)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked in a clearable Select", args = "()", value = ""),
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "end-reached", default = TRUE, about = "triggers when dropdown scroll reaches an end", args = "(direction: 'top' | 'bottom' | 'left' | 'right')", value = "")
    )
  ),
  el_slider = list(
    inputs = list(
      list(input = "", about = "the value, two for a range, once the drag ends")
    ),
    events = list(
      list(event = "input", default = FALSE, about = "triggers when the data changes (It'll be emitted in real time during sliding)", args = "(value: Arrayable<number>)", value = "the value while it is dragged, at most every 200 ms")
    )
  ),
  el_splitter = list(
    inputs = list(),
    events = list(
      list(event = "resize-start", default = FALSE, about = "Triggered when starting to resize a panel, index is the drag bar index", args = "(index: number, sizes: number[])", value = ""),
      list(event = "resize", default = FALSE, about = "Triggered while resizing a panel, index is the drag bar index", args = "(index: number, sizes: number[])", value = "the sizes, at most every 200 ms"),
      list(event = "resize-end", default = TRUE, about = "Triggered when panel resizing ends, index is the drag bar index", args = "(index: number, sizes: number[])", value = ""),
      list(event = "collapse", default = TRUE, about = "Triggered when a panel is collapsed, index is the drag bar index", args = "(index: number, type: 'start' | 'end', sizes: number[])", value = "")
    )
  ),
  el_steps = list(
    inputs = list(),
    events = list(
      list(event = "change", default = FALSE, about = "triggers when the active step changes", args = "(newVal: number, oldVal: number)", value = "")
    )
  ),
  el_switch = list(
    inputs = list(
      list(input = "", about = "`active_value` when on, `inactive_value` when off")
    ),
    events = list()
  ),
  el_table = list(
    inputs = list(
      list(input = "selection_rows", about = "the selected row numbers"),
      list(input = "selection_change", about = "the selected rows, `data[rows, , drop = FALSE]`"),
      list(input = "cell_edit", about = "an edited cell: `list(row, column, value, old)`"),
      list(input = "load", about = "with `lazy = TRUE`, a row asking for its children; answer with `el_load_children()`")
    ),
    events = list(
      list(event = "select", default = FALSE, about = "triggers when user clicks the checkbox in a row", args = "<T = DefaultRow>(selection: T[], row: T)", value = "`list(rows, row_index)`: the selected row numbers, and the row ticked or unticked"),
      list(event = "select-all", default = FALSE, about = "triggers when user clicks the checkbox in table header", args = "<T = DefaultRow>(selection: T[])", value = "`list(rows)`, the selected row numbers"),
      list(event = "cell-mouse-enter", default = FALSE, about = "triggers when hovering into a cell", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T>, cell: HTMLTableCellElement, event: MouseEvent)", value = "`list(row_index, row, column, value)`"),
      list(event = "cell-mouse-leave", default = FALSE, about = "triggers when hovering out of a cell", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T>, cell: HTMLTableCellElement, event: MouseEvent)", value = "`list(row_index, row, column, value)`"),
      list(event = "cell-click", default = FALSE, about = "triggers when clicking a cell", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T>, cell: HTMLTableCellElement, event: PointerEvent)", value = "`list(row_index, row, column, value)`"),
      list(event = "cell-dblclick", default = FALSE, about = "triggers when double clicking a cell", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T>, cell: HTMLTableCellElement, event: MouseEvent)", value = "`list(row_index, row, column, value)`"),
      list(event = "cell-contextmenu", default = FALSE, about = "triggers when user right clicks on a cell", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T>, cell: HTMLTableCellElement, event: PointerEvent)", value = "`list(row_index, row, column, value)`"),
      list(event = "row-click", default = FALSE, about = "triggers when clicking a row", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T> | null, event: PointerEvent)", value = "`list(row_index, row, column)`"),
      list(event = "row-contextmenu", default = FALSE, about = "triggers when user right clicks on a row", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T> | null, event: PointerEvent)", value = "`list(row_index, row, column)`"),
      list(event = "row-dblclick", default = FALSE, about = "triggers when double clicking a row", args = "<T = DefaultRow>(row: T, column: TableColumnCtx<T> | null, event: MouseEvent)", value = "`list(row_index, row, column)`"),
      list(event = "header-click", default = FALSE, about = "triggers when clicking a column header", args = "<T = DefaultRow>(column: TableColumnCtx<T>, event: PointerEvent)", value = "`list(column, label)`"),
      list(event = "header-contextmenu", default = FALSE, about = "triggers when user right clicks on a column header", args = "<T = DefaultRow>(column: TableColumnCtx<T>, event: PointerEvent)", value = "`list(column, label)`"),
      list(event = "sort-change", default = TRUE, about = "triggers when Table's sorting changes", args = "<T = DefaultRow>(data: {column: TableColumnCtx<T>, prop: string | null, order: TableSortOrder | null })", value = "`list(column, order)`"),
      list(event = "filter-change", default = TRUE, about = "triggers when the table's filter changes", args = "(newFilters: Record<string, string[]>)", value = "the filters, `list(<column key> = values)`"),
      list(event = "current-change", default = TRUE, about = "triggers when current row changes", args = "<T = DefaultRow>(currentRow: T | null, oldCurrentRow: T | null)", value = "`list(row_index, row, previous_index)`"),
      list(event = "header-dragend", default = FALSE, about = "triggers after changing a column's width by dragging the column header's border", args = "<T = DefaultRow>(newWidth: number, oldWidth: number, column: TableColumnCtx<T>, event: MouseEvent)", value = "`list(column, width, previous_width)`"),
      list(event = "expand-change", default = TRUE, about = "triggers when user expands or collapses a row (for expandable table, second param is expandedRows; for tree Table, second param is expanded)", args = "<T = DefaultRow>(row: T, expandedRows: T[]) => void & <T = DefaultRow>(row: T, expanded: boolean)", value = "`list(row_index, expanded)`"),
      list(event = "scroll", default = FALSE, about = "Invoked after scrolled", args = "({ scrollLeft: number, scrollTop: number })", value = "`list(scroll_left, scroll_top)`, at most every 200 ms")
    )
  ),
  el_table_v2 = list(
    inputs = list(),
    events = list(
      list(event = "column-sort", default = TRUE, about = "Invoked when column sorted", args = "object\\<[ColumnSortParam](#typings)\\>", value = ""),
      list(event = "expanded-rows-change", default = FALSE, about = "Invoked when expanded rows changed", args = "[KeyType[]](#typings)", value = ""),
      list(event = "end-reached", default = TRUE, about = "Invoked when the end of the table is reached. The callback contain the remain distance, it is the usually the scrollbar height.", args = "(remainDistance: number)", value = ""),
      list(event = "scroll", default = FALSE, about = "Invoked after scrolling", args = "object\\<[ScrollParams](#typings)\\>", value = "at most every 200 ms"),
      list(event = "rows-rendered", default = FALSE, about = "Invoked when rows are rendered", args = "object\\<[RowsRenderedParams](#typings)\\>", value = "at most every 200 ms"),
      list(event = "row-expand", default = FALSE, about = "Invoked when expand/collapse the tree node by clicking the arrow icon", args = "object\\<[RowExpandParams](#typings)\\>", value = "")
    )
  ),
  el_tabs = list(
    inputs = list(
      list(input = "", about = "the name of the selected tab")
    ),
    events = list(
      list(event = "tab-click", default = FALSE, about = "triggers when a tab is clicked", args = "(pane: TabsPaneContext, ev: Event)", value = "the name of the tab clicked"),
      list(event = "tab-change", default = FALSE, about = "triggers when activeName is changed", args = "(name: TabPaneName)", value = "the name of the tab selected"),
      list(event = "tab-remove", default = TRUE, about = "triggers when tab-remove button is clicked", args = "(name: TabPaneName)", value = "the name of the tab closed"),
      list(event = "tab-add", default = TRUE, about = "triggers when tab-add button is clicked", args = "()", value = ""),
      list(event = "edit", default = FALSE, about = "triggers when tab-add button or tab-remove is clicked", args = "(paneName: TabPaneName | undefined, action: 'remove' | 'add')", value = "`list(target, action)`: the tab's name (`NULL` for an add) and `\"add\"` or `\"remove\"`")
    )
  ),
  el_tag = list(
    inputs = list(
      list(input = "", about = "the number of clicks on the tag, as `actionButton()` reports it"),
      list(input = "close", about = "fires when the user closes it (`closable = TRUE`)")
    ),
    events = list()
  ),
  el_time_picker = list(
    inputs = list(
      list(input = "", about = "the time, two for a range")
    ),
    events = list(
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(e: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(e: FocusEvent)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked in a clearable TimePicker", args = "()", value = ""),
      list(event = "visible-change", default = FALSE, about = "triggers when the TimePicker's dropdown appears/disappears", args = "(visibility: boolean)", value = "")
    )
  ),
  el_time_select = list(
    inputs = list(
      list(input = "", about = "the time")
    ),
    events = list(
      list(event = "blur", default = FALSE, about = "triggers when Input blurs", args = "(event: FocusEvent)", value = ""),
      list(event = "focus", default = FALSE, about = "triggers when Input focuses", args = "(event: FocusEvent)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked in a clearable TimeSelect", args = "()", value = "")
    )
  ),
  el_tooltip = list(
    inputs = list(),
    events = list(
      list(event = "show", default = FALSE, about = "Triggers when tooltip is shown. Passes trigger reason as argument.", args = "(event?: Event)", value = ""),
      list(event = "hide", default = FALSE, about = "Triggers when tooltip is hidden. Passes trigger reason as argument.", args = "(event?: Event)", value = ""),
      list(event = "before-show", default = FALSE, about = "Triggers before tooltip is shown. Passes trigger reason as argument.", args = "(event?: Event)", value = ""),
      list(event = "before-hide", default = FALSE, about = "Triggers before tooltip is hidden. Passes trigger reason as argument.", args = "(event?: Event)", value = "")
    )
  ),
  el_tour = list(
    inputs = list(
      list(input = "", about = "`TRUE` while it is open"),
      list(input = "close", about = "the step it was closed on")
    ),
    events = list(
      list(event = "change", default = TRUE, about = "callback when the step changes", args = "(current: number)", value = "the step, from 0"),
      list(event = "finish", default = TRUE, about = "callback function on finished", args = "()", value = "")
    )
  ),
  el_transfer = list(
    inputs = list(
      list(input = "", about = "the keys on the right")
    ),
    events = list(
      list(event = "change", default = FALSE, about = "triggers when data items change in the right list", args = "(value: TransferKey[], direction: TransferDirection, movedKeys: TransferKey[])", value = "`list(value, direction, moved)`"),
      list(event = "left-check-change", default = FALSE, about = "triggers when end user changes the checked state of any data item in the left list", args = "(value: TransferKey[], movedKeys?: TransferKey[])", value = "`list(checked, changed)`"),
      list(event = "right-check-change", default = FALSE, about = "triggers when end user changes the checked state of any data item in the right list", args = "(value: TransferKey[], movedKeys?: TransferKey[])", value = "`list(checked, changed)`")
    )
  ),
  el_tree = list(
    inputs = list(
      list(input = "", about = "the key of the node last clicked"),
      list(input = "checked", about = "the keys of the checked nodes"),
      list(input = "load", about = "with `lazy = TRUE`, a node asking for its children; answer with `el_load_children()`")
    ),
    events = list(
      list(event = "check-change", default = FALSE, about = "triggers when the selected state of the node changes", args = "three parameters: node object corresponding to the node whose selected state is changed, whether the node is selected, whether node's subtree has selected nodes", value = "`list(data, checked, indeterminate)`"),
      list(event = "current-change", default = FALSE, about = "triggers when current node changes", args = "two parameters: node object corresponding to the current node, node property of TreeNode", value = "`list(data, key, level)` of the current node"),
      list(event = "node-expand", default = FALSE, about = "triggers when current node open", args = "three parameters: node object corresponding to the node opened, node property of TreeNode, TreeNode itself", value = "`list(data, key, level)`"),
      list(event = "node-collapse", default = FALSE, about = "triggers when current node close", args = "three parameters: node object corresponding to the node closed, node property of TreeNode, TreeNode itself", value = "`list(data, key, level)`"),
      list(event = "node-contextmenu", default = FALSE, about = "triggers when a node is clicked by right button", args = "four parameters: event, node object corresponding to the node clicked, node property of TreeNode, TreeNode itself", value = "`list(data, key, level)`"),
      list(event = "node-drag-start", default = FALSE, about = "triggers when dragging starts", args = "two parameters: node object corresponding to the dragging node, event.", value = "`list(data)` of the dragged node"),
      list(event = "node-drag-enter", default = FALSE, about = "triggers when the dragging node enters another node", args = "three parameters: node object corresponding to the dragging node, node object corresponding to the entering node, event.", value = "`list(dragging, drop)`, the nodes' data"),
      list(event = "node-drag-leave", default = FALSE, about = "triggers when the dragging node leaves a node", args = "three parameters: node object corresponding to the dragging node, node object corresponding to the leaving node, event.", value = "`list(dragging, drop)`, the nodes' data"),
      list(event = "node-drag-over", default = FALSE, about = "triggers when dragging over a node (like mouseover event)", args = "three parameters: node object corresponding to the dragging node, node object corresponding to the dragging over node, event.", value = "`list(dragging, drop)`, the nodes' data, at most every 200 ms"),
      list(event = "node-drag-end", default = FALSE, about = "triggers when dragging ends", args = "four parameters: node object corresponding to the dragging node, node object corresponding to the dragging end node (may be undefined), node drop type (before / after / inner), event.", value = "`list(dragging, drop, type)`"),
      list(event = "node-drop", default = FALSE, about = "triggers after the dragging node is dropped", args = "four parameters: node object corresponding to the dragging node, node object corresponding to the dropped node, node drop type (before / after / inner), event.", value = "`list(dragging, drop, type)`: `type` `\"before\"`, `\"after\"` or `\"inner\"`")
    )
  ),
  el_tree_select = list(
    inputs = list(
      list(input = "", about = "the value, several with `multiple`"),
      list(input = "load", about = "with `lazy = TRUE`, a node asking for its children; answer with `el_load_children()`")
    ),
    events = list(
      list(event = "visible-change", default = FALSE, about = "triggers when the dropdown appears/disappears", args = "(visible: boolean)", value = ""),
      list(event = "clear", default = FALSE, about = "triggers when the clear icon is clicked in a clearable Select", args = "()", value = ""),
      list(event = "remove-tag", default = FALSE, about = "triggers when a tag is removed in multiple mode", args = "(tagValue: any)", value = ""),
      list(event = "node-click", default = FALSE, about = "triggers when a node is clicked", args = "four parameters: node object corresponding to the node clicked, node property of TreeNode, TreeNode itself, event object", value = ""),
      list(event = "check", default = FALSE, about = "triggers after clicking the checkbox of a node", args = "two parameters: node object corresponding to the node that is checked / unchecked, tree checked status object which has four props: checkedNodes, checkedKeys, halfCheckedNodes, halfCheckedKeys", value = "")
    )
  ),
  el_tree_v2 = list(
    inputs = list(),
    events = list(
      list(event = "node-click", default = TRUE, about = "triggers when a node is clicked", args = "(data: TreeNodeData, node: TreeNode, e: MouseEvent)", value = ""),
      list(event = "node-drop", default = FALSE, about = "triggers when drag something and drop on a node", args = "(data: TreeNodeData, node: TreeNode, e: DragEvent)", value = ""),
      list(event = "node-contextmenu", default = FALSE, about = "triggers when a node is clicked by right button", args = "(e: Event, data: TreeNodeData, node: TreeNode)", value = ""),
      list(event = "check-change", default = FALSE, about = "triggers when the selected state of the node changes", args = "(data: TreeNodeData, checked: boolean)", value = ""),
      list(event = "check", default = TRUE, about = "triggers after clicking the checkbox of a node", args = "(data: TreeNodeData, info: { checkedKeys: TreeKey[],checkedNodes: TreeData, halfCheckedKeys: TreeKey[], halfCheckedNodes: TreeData,})", value = ""),
      list(event = "current-change", default = FALSE, about = "triggers when current node changes", args = "(data: TreeNodeData, node: TreeNode)", value = ""),
      list(event = "node-expand", default = FALSE, about = "triggers when current node open", args = "(data: TreeNodeData, node: TreeNode)", value = ""),
      list(event = "node-collapse", default = FALSE, about = "triggers when current node close", args = "(data: TreeNodeData, node: TreeNode)", value = "")
    )
  ),
  el_upload = list(
    inputs = list(
      list(input = "", about = "the files, as `fileInput()` reports them (without `action`)"),
      list(input = "success", about = "with `action`, the names of the files uploaded"),
      list(input = "error", about = "the name of a file that failed")
    ),
    events = list()
  )
)
